export const USER_REGISTER = 'USER_REGISTER';
export const USER_REGISTER_FULFILLED = 'USER_REGISTER_FULFILLED';
export const USER_REGISTER_REJECTED = 'USER_REGISTER_REJECTED';
export const USER_LOGIN = 'USER_LOGIN';
export const USER_LOGIN_FULFILLED = 'USER_LOGIN_FULFILLED';
export const USER_LOGIN_REJECTED = 'USER_LOGIN_REJECTED';
export const USER_UPDATE = 'USER_UPDATE';
